### ISSUE TITLE
Problems on building with Xcode 7.3

### ISSUE THREAD

**Issue by clsource** [nesdk/ne_example_app#1]
Hello, 
I downloaded the example project. But I could not build as is.

First I installed the pods in 
`pod install`

Then it shows this error

```
ne_example_app-master/Example/ViewController.swift:23:24: 'NEContextManager' is unavailable: cannot find Swift declaration for this class
```

I suppose I must include the SDK
:)

**Comment by vladvelici** [comment]
Hi,

I assume you have a copy of the SDK. We wrote a guide on how to include it at http://www.numbereight.me/blog/installation-instructions.

Thanks for trying it out. :)

**Comment by clsource** [comment]
Hello, 
I posted a more detailed question in the forums

https://groups.google.com/a/numbereight.me/forum/#!topic/support/WlZBUbnQMBk

:)
